### ISSUE TITLE
If condition is not working while writing to log file

### ISSUE THREAD

**Issue by operabeats** [tobixen/thrash-protect#15]
I have noticed a strange thing, in ```log_frozen``` and ```log_unfrozen``` functions, the test for ```config.log_user_data_on_freeze``` variable is not working properly. my python version is 3.6.4:

```
[manjaro@manj-pc thrash-protect]$ python
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from os import getenv, kill, getpid, unlink, getpgid, getsid
>>> class config:
...     log_user_data_on_unfreeze = int(getenv('THRASH_PROTECT_LOG_USER_DATA_ON_UNFREEZE', '1'))
... 
>>> if config.log_user_data_on_unfreeze:
...     print ("Log user data")
... else:
...     print ("No User data")
... 
Log user data
```
Is this some python version specific issue OR do I need to set any environment variables? ( I have both python 3.6 and 2.7).

Also how do I make the script less aggressive - Increasing ```THRASH_PROTECT_INTERVAL``` to 2sec and ```THRASH_PROTECT_SWAP_PAGE_THRESHOLD``` to 16?

**Comment by tobixen** [comment]
Things seems to work as intended above, the default value for log_user_data_on_unfreeze is true, and that's what you get.

So far, configuration options have to be passed through the environment, like this:

    env THRASH_PROTECT_LOG_USER_DATA_ON_UNFREEZE=0 python ./thrash-protect

I should probably consider to add support for passing configuration through argparse and/or a config file.  Anyway, I've been happy with the defaults on all systems where I'm running thrash-protect, hence the configuration part is neither well-tested nor well-implemented.

Logging is also a bit of a problem, I really should do some work on it, using the logging module consistently.

**Comment by operabeats** [comment]
Ooops sorry! I was completely in *nix world and thinking 0 is true and 1 is false. The script is working perfectly.

I have added a wiki page on setting environment variables. I am running this script as systemd service, so added a line to set variables for that as well.

Also please let me know I am right to assume if I increase ```THRASH_PROTECT_INTERVAL``` I have to increase ```THRASH_PROTECT_SWAP_PAGE_THRESHOLD``` proportionately.

**Comment by tobixen** [comment]
Seems correct, the threshold check is a simple `delta > threshold`-check, not a `delta / interval > threshold`-check.

**Comment by operabeats** [comment]
Closing this issue as this is an incorrect bug report.
