### ISSUE TITLE
At around line 138 "/" should be changed to "//" for integer division

### ISSUE THREAD

**Issue by operabeats** [tobixen/thrash-protect#16]
Around line 138, single "/" should be double slash "//" for integer division (without that irrespective of threshold setting, it keeps stopping processes).

```
            ((self.swapcount[0]-prev.swapcount[0])//config.swap_page_threshold + 1.0) *
            ((self.swapcount[1]-prev.swapcount[1])//config.swap_page_threshold + 1.0)
```
Reference: https://stackoverflow.com/a/39332574

**Comment by tobixen** [comment]
Hm, may be several bugs here.  I'll look into it.

I think that what I intended here was float division, not integer division - and the current construct is buggy, because it will behave differently in python2 and python3.

    $ python3 -c 'print(3/2)'
    1.5

vs

    $ python2 -c 'print(3/2)'
    1

There are at least three ways to force through float division, either as the stackoverflow suggests:

    from __future__ import division

or casting either the divisor or dividend into a float.

**Comment by tobixen** [comment]
Hm ... that's probably not how it was intended to be.  I need to look more into this.

**Comment by tobixen** [comment]
Would you care to review and test the changeset?

**Comment by operabeats** [comment]
I am not sure, but as per my test, using integer division with "//" will satisfy all conditions.

if  swap delta is less than threshold then integer division results in "0". Adding one to it, ensures if swap delta is less than threshold, the value is "1" (and 2 / 3 / 4 ... for delta larger than threshold)

this is same for swap[0] and swap[1]

the product will remain "1" as long as both swap[0] and swap[1] delta remains below threshold.

Here is my test run
```
>>> config_swap_page_threshold=4
>>> self_swapcount_0=12
>>> prev_swapcount_0=10
>>> self_swapcount_1=20
>>> prev_swapcount_1=20
>>> ret = (
...     ((self_swapcount_0-prev_swapcount_0)//config_swap_page_threshold + 1.0) *
...     ((self_swapcount_1-prev_swapcount_1)//config_swap_page_threshold + 1.0)
...     > 1.0)
>>> print (ret)
False
>>> ## swap count less than threshold, so ret is False
... 
>>> 
>>> self_swapcount_0=14  ## set one way swap equal to threshold
>>> 
>>> ret = (
...     ((self_swapcount_0-prev_swapcount_0)//config_swap_page_threshold + 1.0) *
...     ((self_swapcount_1-prev_swapcount_1)//config_swap_page_threshold + 1.0)
...     > 1.0)
>>> print (ret)
True
>>> ## swap is equal to threshold, do ret is True
... 
>>> 
>>> self_swapcount_0=10  ## set swap_0 to zero and test with swap_1
>>> 
>>> self_swapcount_1=22  ## set less than threshold, and we expect False
>>> 
>>> ret = (
...     ((self_swapcount_0-prev_swapcount_0)//config_swap_page_threshold + 1.0) *
...     ((self_swapcount_1-prev_swapcount_1)//config_swap_page_threshold + 1.0)
...     > 1.0)
>>> 
>>> print (ret)
False
>>> ## still works as expected
... 
>>> 
>>> ## now lets test with large swap_1 value
... 
>>> self_swapcount_1=200
>>> 
>>> ret = (
...     ((self_swapcount_0-prev_swapcount_0)//config_swap_page_threshold + 1.0) *
...     ((self_swapcount_1-prev_swapcount_1)//config_swap_page_threshold + 1.0)
...     > 1.0)
>>> 
>>> print (ret)
True
>>> ## ret is True as expected
```

**Comment by operabeats** [comment]
Ignore my previous comment. Now I understood the logic...

_for the second part  (when one way swap is zero and other way swap is very large, we should trigger), we need floating point arithmetic._

I am loading it to my system. Will let you know how it works.

**Comment by operabeats** [comment]
I had been running this new code for around 10 hours, and it seems to be working fine. Earlier here used be bout of freezing and unfreezing whenever there was an instance of swapping and browser used to become frozen frequently making it difficult use.

Now, with new code, browser windows are responsive, while thrash-protect does its work.

**Comment by tobixen** [comment]
That's embarrassing that such an obvious bug has been standing there for such a long time.  Obviously I ought to make more unit tests.
