### ISSUE TITLE
[Request] Is it possible to check for foreground process while freezing

### ISSUE THREAD

**Issue by operabeats** [tobixen/thrash-protect#17]
This is a request, which helps using this on laptops / workstations.

Is it possible to check if the process about to be frozen, is a foreground process and if so, skip to next PID in queue (like we do for the self PID)

**Comment by tobixen** [comment]
How to identify a "foreground process"?  The best I've come up with is the command name whitelist.

**Comment by operabeats** [comment]
I just tried to get active window PID on Linux with xprop command. There is a problem with chrome in finding active window. Irrespective of which chrome window or tab is in focus, it always returns the PID of main chrome browser process.

This may not be possible to implement...

**Comment by tobixen** [comment]
I'm wondering if the fix #16 has reduced the need for this.

Theoretically, one or more chromium browser tabs should start behaving sluggishly if thrash-protect kicks in.  Personally I have experienced all of chromium becoming very much  sluggish ... but most likely, the alternative without thrash protect would be that the whole workstation or laptop becomes unresponsive.  With chromium one can simply kill the pids that are consuming too much memory, without the whole browser going down, that's a nice thing when chromium is so bogged down it's a lot of time consume just to click on the "close tab"-buttons.
