### ISSUE TITLE
Too many "unacceptable time delta observed!" error messages

### ISSUE THREAD

**Issue by operabeats** [tobixen/thrash-protect#18]
I am using thrash protect with default settings, except for the whitelist and log user data on freeze (I will provide config file below for this).

I have been seeing LOT of "unacceptable time delta observed!" messages in the journal logs. Is there a way to resolve this issue?

My laptop is an old inspiron 1520 with core 2 processor, 4GB RAM and  160 Gb HDD@5400rpm.

The journal log is a snapshot for a minute, there are such messages for every minute, filling my journal log

**System Details**:
```
CPU~Dual core Intel Core2 Duo T7300 (-MCP-) 
speed/max~1572/2001 MHz 
Kernel~4.14.27-1-MANJARO x86_64

free command output:
              total        used        free      shared  buff/cache   available
Mem:           3947        3585         113          23         248         159
Swap:          8191        1776        6415
 ```

**thrash-protect log**:
```2018-03-22 07:43:56 - unfrozen pid 5993
2018-03-22 07:47:52 - frozen   pid  5993 - u:   manjaro  CPU:  1.3%  MEM:  4.2%  CMD: /usr/lib/chromium/chromium - list: [(5993,)]
2018-03-22 07:47:53 - frozen   pid  6388 - u:   manjaro  CPU:  0.7%  MEM:  6.0%  CMD: /usr/lib/chromium/chromium - list: [(5993,), (6388,)]
2018-03-22 07:47:54 - frozen   pid  6007 - u:   manjaro  CPU:  1.1%  MEM:  5.5%  CMD: /usr/lib/chromium/chromium - list: [(5993,), (6388,), (6007,)]
2018-03-22 07:47:54 - frozen   pid  6372 - u:   manjaro  CPU:  0.6%  MEM:  4.0%  CMD: /usr/lib/chromium/chromium - list: [(5993,), (6388,), (6007,), (6372,)]
2018-03-22 07:47:57 - unfrozen pid 6372
2018-03-22 07:47:57 - unfrozen pid 6007
2018-03-22 07:47:58 - unfrozen pid 5993
2018-03-22 07:47:58 - unfrozen pid 6388
2018-03-22 07:48:11 - frozen   pid  5993 - u:   manjaro  CPU:  1.3%  MEM:  4.0%  CMD: /usr/lib/chromium/chromium - list: [(5993,)]
2018-03-22 07:48:12 - frozen   pid  6388 - u:   manjaro  CPU:  0.7%  MEM:  6.0%  CMD: /usr/lib/chromium/chromium - list: [(5993,), (6388,)]
2018-03-22 07:48:13 - unfrozen pid 6388
2018-03-22 07:48:13 - unfrozen pid 5993
```

**journal log**:
```Mar 22 07:46:16 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:30 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:45 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:48 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:49 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:49 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:49 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:49 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:50 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:51 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:52 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:52 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:52 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:53 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:53 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:54 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:54 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:54 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:54 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:55 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:55 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:55 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:47:59 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
Mar 22 07:48:03 manjaro-pc thrash-protect[15846]: ERROR:root:red alert!  unacceptable time delta observed!
```
**thrash-protect environment variable config**:
```
cat /etc/systemd/system/thrash-protect.service.d/override.conf
[Service]
Environment="THRASH_PROTECT_CMD_WHITELIST=sshd bash -bash sudo xinit X SCREEN ssh xterm xfce4-terminal Xorg xfwm4 systemd-journal journalctl i3lock xautolock ncdu vim Thunar  xfce4-power-manager NetworkManager"
Environment="THRASH_PROTECT_LOG_USER_DATA_ON_FREEZE=1"
#Environment="THRASH_PROTECT_SWAP_PAGE_THRESHOLD=8"
#Environment="THRASH_PROTECT_DATE_HUMAN_READABLE=1"
#Environment="THRASH_PROTECT_LOG_USER_DATA_ON_UNFREEZE=0"
#Environment="THRASH_PROTECT_INTERVAL=1"
```

**Comment by tobixen** [comment]
Some thoughts:

* Logging is something that should be worked with.  The thing you see in the syslog comes via "logging.error", while the logging of processes suspended and started is written to a log file outside the logging module.  I think it makes sense to run everything through the logging module (except for the /tmp/thrash-protect-frozen-pid-list - it's not a log file per se - the file name should be made configurable and possibly the location should be defaulted to /var/lib rather than /tmp, but except for that I think it's worth keeping), and possibly set up default logging configuration such that logging still goes to the same file.  At the other hand, it probably makes even more sense to run the logging via the systemd journal when applicable.  It may even be that my systems also frequently hit this one, but I don't see it as it's not coming to the log file(s) I'm monitoring. (should probably look a bit into ELK).

* config.max_acceptable_time_delta is hardcoded to interval/16.0, perhaps it should be made adjustable, or perhaps the threshold should be lowered.  However, I'm wondering if the fix for issue #16 may have solved this problem for you?

* Can you fix the code to log the debug info?  (check around line 93).

* Experimenting with the interval (THRASH_PROTECT_INTERVAL) may help.  What is being monitored is the time passing while the script is doing its work; this time should be neligible.  If the server is just generally very slow (like in old or overloaded CPU, but enough memory), increasing THRASH_PROTECT_INTERVAL may help (as it also increases the config.max_acceptable_time_delta, and reduces the overhead caused by thrash protect).  If things are going slow because the box is heavily thrashed, decreasing the THRASH_PROTECT_INTERVAL (and maybe the threshold as well) may help as it may protect the machine from thrashing in the first place.

**Comment by operabeats** [comment]
I am planning to print variable "delta" also with the message, so that I know how much time does it take to execute the script during various stages.

I may also add CPU load to it...

Is there any variable that can indicate swap load, that I can print?

for now I have reduced the ```config.max_acceptable_time_delta``` to interval/8, but still there are messages in the log

**Comment by operabeats** [comment]
before I play around with `config.max_acceptable_time_delta` value, I want to understand the implications of this. What does the script do when `delta` is greater than `config.max_acceptable_time_delta` 

Currently I am just printing `delta` with the message. based on that I will change the values. so far the `delta` is around .07 to .08

If its not critical to log on to journal log, I would prefer it to be written to /var/log/thrash-protect.log

**Comment by tobixen** [comment]
The rationale for this check is that if the system is so bogged down that the thrash-protect script barely manages to turn around, it should assume the system is thrashing.  The cooldown-counter is increased.

The cooldown-counter regulates two things:

* sleep interval between each run is reduced, the bigger the counter is.
* processes can only be unfrozen if the counter is 0.

Hence, a too low value of max_acceptable_time_delta may cause processes to get suspended forever.

If the observed delta is as high as 80 ms on a modern system that isn't thrashing, then the default value seems way too low.

**Comment by tobixen** [comment]
Obviously systems are different, and the results of running thrash-protect on a "slow" system will be uncontrolled suspension of too many processes.  I'll think a bit on this one and either remove this test completely or make some safety valves.

**Comment by tobixen** [comment]
I believe I've solved this problem ... though I'm not sure if this is the best way to solve it, but anyway.

If things are "too slow", but no thrashing is observed, then increase the threshold slightly.  If things aren't "too slow", but thrashing is observed, then decrease the threshold slightly.

I've tested the change by running it with a very low interval - the max_acceptable_delta is hard-coded to interval/16, so with a sufficiently low interval the max_acceptable_delta also gets too low.  Eventually max_acceptable_delta stabilizes at some sane value.

**Comment by hakavlad** [comment]
Seems like problem is not solved. I saw warnings (`WARNING:root:red alert!  unacceptable time delta observed! interval`) again with default settings.

**Comment by tobixen** [comment]
It's downgraded from an error to a warning, and eventually the threshold will autoadjust itself so the messages will stop coming frequently.

**Comment by tobixen** [comment]
This autoadjust idea caused the "red alert"-warnings to pop up at _any_ system, no matter if it's thrashing or not, and no matter if it's an ultra fast or ultra slow system.  It was irking me a bit, so I made some adjustments to make it come less frequently and replaced the "red alert" and "unacceptable" with a note that it should be expected to see that error message every now and then.  The work "leaked" in through an unrelated commit 60fcadc5afe026698747769cc227270b7faa0e38
