### ISSUE TITLE
Wrong order of selectors?

### ISSUE THREAD

**Issue by Niektory** [tobixen/thrash-protect#31]
https://github.com/tobixen/thrash-protect/blob/90c0a7e442d5e1118a40b4755530f0049dedb79f/thrash-protect.py#L377-L378

Is this order right? The [README](https://github.com/tobixen/thrash-protect/blob/master/README.rst#implementation-details) seems to suggest that `OOMScoreProcessSelector()` should be before `PageFaultingProcessSelector()`.

**Comment by tobixen** [comment]
Hm, good point.  I'll fix it in the master branch as for now.  Leaving the issue open as I should try to do some performance testing with and without this patch before making a new release.
