### ISSUE TITLE
thrash-protect gets killed

### ISSUE THREAD

**Issue by bounlu** [tobixen/thrash-protect#37]
It often gets killed with the below error:

```
$sudo thrash-protect
...
WARNING:root:relatively big time delta observed. interval: 0.5 cooldown_counter: 0 expected delay: 0 max acceptable delta: 0.16210890375625014 delta: 0.6467616558074951 time: 1621679841.8632085 frozen pids: [(2839,), (3728,)].  (this message is to be expected every now and then as the max acceptable delta parameter is autotuned)
WARNING:root:relatively big time delta observed. interval: 0.5 cooldown_counter: 2 expected delay: 0 max acceptable delta: 0.16210890375625014 delta: 0.8485774993896484 time: 1621679842.7120879 frozen pids: [(2839,), (3728,), (101220,)].  (this message is to be expected every now and then as the max acceptable delta parameter is autotuned)
Traceback (most recent call last):
  File "/usr/sbin/thrash-protect", line 607, in main
    thrash_protect(args)
  File "/usr/sbin/thrash-protect", line 553, in thrash_protect
    freeze_something()
  File "/usr/sbin/thrash-protect", line 470, in freeze_something
    pids_to_freeze = pids_to_freeze or global_process_selector.scan()
  File "/usr/sbin/thrash-protect", line 397, in scan
    ret = self.collection[self.scan_method_count % len(self.collection)].scan()
  File "/usr/sbin/thrash-protect", line 258, in scan
    stats = self.readStat(pid)
  File "/usr/sbin/thrash-protect", line 212, in readStat
    stats_tx = stat_file.read().decode('utf-8', 'ignore')
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/thrash-protect", line 616, in <module>
    main()
  File "/usr/sbin/thrash-protect", line 612, in main
    kill(pid_to_unfreeze, signal.SIGCONT)
TypeError: an integer is required (got type tuple)
```

**Comment by hakavlad** [comment]
It's not "Killed". It's an exception in the script that  should be handled.

>ProcessLookupError: [Errno 3] No such process

Seems like t-protect tried to unfreeze the process, but the process has already died.

**Comment by tobixen** [comment]
Definitively a bug.  What version is it?

**Comment by tobixen** [comment]
> Seems like t-protect tried to unfreeze the process, but the process has already died.

Close, but not quite right.  I do have a try-except to catch the event that the process has already exited, both in the freeze and unfreeze section of the code.

This is in the logic for finding out what process to freeze.  The most likely explanation is that it's trying to find stats on a process that has already exited.  I'll throw a try-except-clause around it.

It's a bit weird though, because it attempts to do a `file.read()` and it ends up with a `ProcessLookupError`.  The file that it's trying to read is `/proc/$pid/stat`.  If the process have exited, I would expect to get a FileNotFound-error rather than a ProcessLookupError.

**Comment by tobixen** [comment]
There is a second error also, that's brand new, untested logic - if the program crashes for whatever reason, it should try to resume all processes that it has already suspended (this may be a pretty bad idea - but if systemd starts up thrash-protect again, then it's better not to have those processes suspended forever).

**Comment by bounlu** [comment]
Thanks both for quick replies.

@tobixen Yes, I downloaded the latest release version 0.14.0

I agree that those frozen processes should be resumed before program exits for whatever reason. Otherwise I noticed that those processes remained in the state T and I had to send SIGCONT signal to them manually to resume. Because restarting the program didn't recognise those PIDs anymore in the frozen list.

**Comment by tobixen** [comment]
You may try to download the master version and check if it works for you.  I wrote a quickfix, but haven't tested it myself yet.

**Comment by tobixen** [comment]
> Because restarting the program didn't recognise those PIDs anymore in the frozen list.

That's a third bug indeed, another untested feature I put into the code recently - it should read the frozen list (if it exists) at startup and unfreeze those processes.

I will try to write up test code for those three cases.  Sorry for the bad workflow practices.  I was in a bit of a rush getting 0.14.0 pushed out before starting on other projects.

**Comment by tobixen** [comment]
> That's a third bug indeed, another untested feature I put into the code recently - it should read the frozen list (if it exists) at startup and unfreeze those processes.

I'm partially wrong at this account at least, `unfreeze_from_tmpfile` actually has unit test code, and the unit test passes.

I'll have to try and verify the logic manually.

**Comment by tobixen** [comment]
Release 0.14.1 is out, should fix the issues properly (except, I was not able to reproduce  the last reported one - that thrash-protect wouldn't automatically resume processes frozen during the previous run of thrash_protect)

**Comment by bounlu** [comment]
Thanks a lot for the speedy action! I installed the patch and hopefully it will be fine, will let you know if anything goes wrong.
